version: "3.7"


services:

  postgres:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: assembly_voting_user
      POSTGRES_PASSWORD: 1O5A2N3Wgpps
      POSTGRES_DB: assembly_db
    ports:
      - 5431:5432

  application:
    build: ./
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: dockerized
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    depends_on:
      - "postgres"